#Para executar o projeto use "--spring.profiles.active=local" para selecionar um perfil

server:
   port: 1000

spring:
    jpa:
        database: HSQL
        show-sql: true
        hibernate:
             ddl-auto: create-drop
             
    datasource:
        url: jdbc:hsqldb:file:mydb;sql.syntax_mys=true;
        username: sa
        password: 
        driver-class-name: org.hsqldb.jdbc.JDBCDriver

logging.level.root: INFO
info.app.name=@project.name@
info.app.description=@project.description@
info.app.version=@project.version@
info.app.commitid=@commitid@
endpoints.shutdown.enabled=true


        

   
