#Para executar o projeto use "--spring.profiles.active=local" para selecionar um perfil

server:
   port: 80

spring:
    jpa:
        database: HSQL
        show-sql: true
        hibernate:
             ddl-auto: create-drop
             
    datasource:
        url: jdbc:hsqldb:file:mydb;sql.syntax_mys=true;
        username: sa
        password: 
        driver-class-name: org.hsqldb.jdbc.JDBCDriver

logging.level.root: INFO


        

   